### ISSUE TITLE
Document Linux dependency on X11

### ISSUE THREAD

**Issue by dtoso-skymesh** [hoytech/Alien-Electron#2]
Was trying to install this module inside Docker (build time) but a test failed. On further investigation, Electron binary itself is silently failing when no X11 `$DISPLAY` is available.

Most of the CPAN testers fail outputs have the same test failure so I guess they're failing for the same reason -- i.e: they don't have X11 available at module builds.

A workaround that relies on `Xvfb` is as follows:

```
RUN (Xvfb :1 &) && \
    export DISPLAY=":1" && \
    sleep 5 && \
    cpanm Alien::Electron && \
    rm -rf /tmp/.X*
```

Perhaps `Alien::Electron` should document this **build** dependency?

Obviously, the same applies for `Valence` and I'll raise the same issue there.

**Comment by hoytech** [comment]
Thanks! Added to the docs: 5a7b4eca9a894fdbc11a7959df87e4d1d7c7f43a

I'll release it shortly. I may as well upgrade electron too while I'm doing a release.
