### ISSUE TITLE
Upgrade to Election 2.0.0

### ISSUE THREAD

**Issue by sanko** [hoytech/Alien-Electron#5]
[Stable 2.0.0 of Electron](https://electronjs.org/releases#2.0.0) has been out a few weeks now, is there any chance Alien::Electron will move to a more up to date version to install? To continue using Valence, I've had to manually upgrade the binary for bug fixes and new features for some time now because Alien::Electron installs 1.4.1 which is nearly two years old.

**Comment by hoytech** [comment]
I just uploaded Alien::Electron 0.200 to CPAN:

https://metacpan.org/release/FRACTAL/Alien-Electron-0.200

This package installs electron 2.0.1 which has some security fixes over 2.0.0. Thanks for reminding me to update this, and let me know if you have encounter any issues.
